### ISSUE TITLE
Missing pickle file (or perhaps a misspelled file path) 

### ISSUE THREAD

**Issue by courtyardz** [bevesce/TodoFlow#11]
When ply calls its internal function `yacc(...,picklefile=None)`, it is calling it with a picklefile that does not exist: `/Users/my_account/.todoflow_parsetab.pickle`. Please see my simple script below and the error output. Notice that in the last line of the error output, there is a `u` in front of the file path. This may be causing the issue, but I haven't yet found out when it gets put there...

FYI I am running El Cap public beta, ply (3.6), Todoflow (4.0.1). Perhaps this is instead a ply issue?

### todoflow_now.py:
```python
#!/usr/local/bin/python
# return query of tasks to be added to reminders Now list

import sys
import os
import time

#sys.path.append('/usr/local/lib/python2.7/site-packages/')
import todoflow

curDate = time.strftime("%Y-%m-%d")
todos = todoflow.from_path('~/Dropbox/Notes/test.taskpaper')

#def get_project(iterable):

for item in todos.search('((@today or @focus or @overdue or @next or @due <= ' & curDate & ' ) and not @done)+d'):
    print item
    #item.tag('@done', curDate)
    #item.remove_tag('@today')
```
### error messages:
```python
$ todoflow_now.py 
Traceback (most recent call last):
  File "/Users/my_account/bin/todoflow_now.py", line 8, in <module>
    import todoflow
  File "/usr/local/lib/python2.7/site-packages/todoflow/__init__.py", line 3, in <module>
    from .todoflow import from_text, from_path, from_paths, from_dir
  File "/usr/local/lib/python2.7/site-packages/todoflow/todoflow.py", line 4, in <module>
    from .parser import parse
  File "/usr/local/lib/python2.7/site-packages/todoflow/parser.py", line 4, in <module>
    from .todos import Todos, Node
  File "/usr/local/lib/python2.7/site-packages/todoflow/todos.py", line 5, in <module>
    from .querying_parser import parse as parse_query
  File "/usr/local/lib/python2.7/site-packages/todoflow/querying_parser.py", line 247, in <module>
    debug=0, write_tables=0,
  File "/usr/local/lib/python2.7/site-packages/ply/yacc.py", line 3242, in yacc
    read_signature = lr.read_pickle(picklefile)
  File "/usr/local/lib/python2.7/site-packages/ply/yacc.py", line 1986, in read_pickle
    in_f = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/Users/my_account/.todoflow_parsetab.pickle'
```

**Comment by mandel01** [comment]
Thanks for all of your work on this utility! On Mac OS X 10.10 (Yosemite) I get the same issue. The unicode prefix prints in Python 2.7 (pip install... using the command shown) but not in Python 3.4 (installed via homebrew python 3). I tried copying the <A HREF = "https://github.com/bevesce/TodoFlow/blob/master/todoflow_parsetab.pickle">file</A> from the repo and saving it in my root, but then it exited with `ImportError: cannot import name 'query'`. It seems like the pip command is not installing all of the files?

```
DMI-MBPro2-mandel:~ markmandel$ python2.7
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import todoflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/todoflow/__init__.py", line 3, in <module>
    from .todoflow import from_text, from_path, from_paths, from_dir
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/todoflow/todoflow.py", line 4, in <module>
    from .parser import parse
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/todoflow/parser.py", line 4, in <module>
    from .todos import Todos, Node
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/todoflow/todos.py", line 5, in <module>
    from .querying_parser import parse as parse_query
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/todoflow/querying_parser.py", line 247, in <module>
    debug=0, write_tables=0,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ply/yacc.py", line 3242, in yacc
    read_signature = lr.read_pickle(picklefile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ply/yacc.py", line 1986, in read_pickle
    in_f = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/Users/markmandel/.todoflow_parsetab.pickle'
DMI-MBPro2-mandel:~ markmandel$ python3
Python 3.4.3 (default, Jul 13 2015, 12:18:23) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import todoflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/todoflow/__init__.py", line 3, in <module>
    from .todoflow import from_text, from_path, from_paths, from_dir
  File "/usr/local/lib/python3.4/site-packages/todoflow/todoflow.py", line 4, in <module>
    from .parser import parse
  File "/usr/local/lib/python3.4/site-packages/todoflow/parser.py", line 4, in <module>
    from .todos import Todos, Node
  File "/usr/local/lib/python3.4/site-packages/todoflow/todos.py", line 5, in <module>
    from .querying_parser import parse as parse_query
  File "/usr/local/lib/python3.4/site-packages/todoflow/querying_parser.py", line 247, in <module>
    debug=0, write_tables=0,
  File "/usr/local/lib/python3.4/site-packages/ply/yacc.py", line 3242, in yacc
    read_signature = lr.read_pickle(picklefile)
  File "/usr/local/lib/python3.4/site-packages/ply/yacc.py", line 1986, in read_pickle
    in_f = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/markmandel/.todoflow_parsetab.pickle'
>>> import todoflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/todoflow/__init__.py", line 3, in <module>
    from .todoflow import from_text, from_path, from_paths, from_dir
  File "/usr/local/lib/python3.4/site-packages/todoflow/todoflow.py", line 4, in <module>
    from .parser import parse
  File "/usr/local/lib/python3.4/site-packages/todoflow/parser.py", line 4, in <module>
    from .todos import Todos, Node
  File "/usr/local/lib/python3.4/site-packages/todoflow/todos.py", line 5, in <module>
    from .querying_parser import parse as parse_query
  File "/usr/local/lib/python3.4/site-packages/todoflow/querying_parser.py", line 9, in <module>
    from . import query
ImportError: cannot import name 'query'
```

**Comment by courtyardz** [comment]
@mandel01, I also posted this issue under the ply project. Please see a response there for a fix, a two-line existence check in yacc.py on the pickle file prior to an access attempt.

**Comment by mandel01** [comment]
Ah, clever. Thank you!

**Comment by bevesce** [comment]
I removed this pickle file altogether, so It should work out of the box.
